config/routes.rb
Tripper::Application.routes.draw do
  devise_for :users

  match 'map/new_place' => 'map#new_place'
  match 'map/index' => 'map#index'
  match 'places/update_location' => 'places#update_location'

  resources :places
  resources :users
  resources :home
  resources :comments

  resources :comments do
    resources :comments
  end

  resources :places do
    resources :comments
  end

  get "home/index"
  match '/:id' => 'users#show', :as => :user

  root :to => "home#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable, :dependent => :destroy
  belongs_to :user
end

app/models/place.rb
class Place < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :designations, :facilities
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :ratings
  has_many :raters, :through => :ratings, :source => :users
  belongs_to :user
  validates_presence_of :user_id, :message => "must be logged in"
  validates_presence_of :name
  validates_presence_of :address
  validates_presence_of :latitude
  validates_presence_of :longitude

  def author
    if user
      user.email
    else
      "unknown"
    end
  end

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :value

  belongs_to :place
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :login

  has_many :places
  has_many :comments
  validates_presence_of :username
  validates_uniqueness_of :username
  validates_exclusion_of :username, :in => %w( places home )

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  def to_param
    username
  end

  protected
 
  def self.find_for_database_authentication(conditions)
    login = conditions.delete(:login)
    where(conditions).where(["username = :value OR email = :value", { :value => login }]).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
 
  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == 'admin' && password == 'password'
    end
  end

  def tag_string
    ["Campsite", "Restroom", "Shower", "Bear box", "Hike and bike", "Beach wheelchair access", "Bicycle trails", "Boat mooring", "Boat ramps"]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @comment = Comment.new(params[:comment])
    @comment.user = current_user
    @comment.save
    respond_to do |format|
      format.html { redirect_to place_path(@comment.commentable_id) }
      format.js
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @place = @comment.commentable
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to place_path(@place) }
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @places = Place.all.reverse
    @comments = Comment.all.reverse
    @activity = (@places + @comments).sort { |a, b| b.created_at <=> a.created_at }

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @places }
    end
  end

end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @places = Place.all.reverse

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @places }
    end
  end

 def new_place
    @tags = tag_string
    @place = Place.new
    @place.latitude = params[:lat]
    @place.longitude = params[:lng]
    @place.name = params[:name]
    @place.address = params[:address]
    @place.designation_list = params[:designation]
    @place.facility_list = params[:facilities]

    if not @place.latitude and @place.longitude
      render :text => "<h3>Please provide the coordinates of your place.</h3>"
    else
      render :layout => false
    end
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :authenticate_user!, :except => [:show, :index]
  # The map layout is required for loading the google map
  # O switched to application layout cause internets is down.
  layout "map"
  #layout "application"

  # Update Place location
  def update_location
    place = Place.find(params[:id])
    place.latitude = params[:lat]
    place.longitude = params[:lon]
    place.save
    render :text => place.to_json
  end

  # GET /places
  # GET /places.xml
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @places }
    end
  end

  # GET /places/1
  # GET /places/1.xml
  def show
    @place = Place.find(params[:id])
    #@tags = Place.facility_counts
    @tags = tag_string

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # GET /places/new
  # GET /places/new.xml
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
    #@tags = Place.facility_counts
    @tags = tag_string
    unless @place.user == current_user or current_user.admin?
      flash[:error] = "You are not authorized to edit that suggestion."
      redirect_to :action => :home
      return
    end
  end

  # POST /places
  # POST /places.xml
  def create
    unless user_signed_in?
      flash[:error] = "You must be logged in to create a suggestion"
      redirect_to(places_url)
      return
    end

    @place = Place.new(params[:place])
    @place.designation_list = params[:designation]
    @place.facility_list = params[:facilities]
    @place.user = current_user

    respond_to do |format|
      if @place.save
        format.html { redirect_to(@place, :notice => 'Place was successfully created.') }
        format.xml  { render :xml => @place, :status => :created, :location => @place }
        format.js { render :json => @place, :status => :created, :location => @place  }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
        format.js { render :json => { :errors => @place.errors.full_messages } }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.xml
  def update
    @place = Place.find(params[:id])
    @place.designation_list = params[:designation]
    @place.facility_list = params[:facilities]

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to(@place, :notice => 'Place was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.xml
  def destroy
    @place = Place.find(params[:id])
    if current_user and (current_user.admin? or @place.user == current_user)
      @place.destroy
    else
      flash[:error] = "It appears you attempted to delete a suggestion that you did not create. Perhaps you need to log in?"
    end

    respond_to do |format|
      format.html { redirect_to( root_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_username(params[:id])
    @places = @user.places 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)  
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)  
    "http://gravatar.com/avatar/#{gravatar_id}?s=48&d=wavatar&r=pg"  
  end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def icon_image(t, str)
    image_tag("/images/parkIcons/#{t}.gif", :alt => t, :title => t, :class => str)
  end
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment_container" id="comment_<%=comment.id%>">
  <div class="comment">
    <div class="metadata">
      <div>
        <span class="avatar"> <%= link_to image_tag(avatar_url(comment.user)), "/#{comment.user.username}" %></span>  
        <span class="author"> <%= link_to comment.user.username, "/#{comment.user.username}" %> </span>
        <span class="timestamp"> (<%= distance_of_time_in_words_to_now comment.created_at %> ago)</span>
      </div>
      <div class="edit_links">
        <% if user_signed_in? and current_user.admin? %>
          <%= link_to image_tag("remove.png", :alt => 'Destroy Comment'), [comment.commentable, comment], :confirm => 'Are you sure?', :method => :delete, :remote => true %>
          <%= link_to image_tag("reply.png", :alt => 'Reply'), '#', :class=> "reply", :remote => true %>
        <% end %>
        <% if comment.comments.count != 0 %>
          <span><%= link_to pluralize(comment.comments.count, "reply"), '#', :class => "show", :remote => true %></span>
        <% end %>
      </div>
      <div class="comment_content_container">
        <div class="comment_content">
          <%= comment.content %>
        </div>
      </div>
    </div>
  </div>
  <div class="reply_form" style="display:none;">
    <%= render :partial => "comments/reply_form", :object => comment %>
  </div>

  <div class="show_replies" style="display:none;">
    <%= render :partial => "comments/comment", :collection => comment.comments %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for(@commentable, Comment.new) do |f| %>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, :rows => '10' %>
  </div>
  <div class="field" style="display:hidden;">
    <%= f.label :commentable_id %>
    <%= f.text_area  %>
    <%= f.label :commentable_type %>
    <%= f.text_area "place" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_place_form.html.erb
<% place = place_form-%>
<% if user_signed_in? %>
  <p>Add a comment</p>
<div class="comment_head">
  <div class="metadata">
    <div>
      <span class="avatar"> <%= link_to image_tag(avatar_url(current_user)), "/#{current_user.username}" %></span>  
    </div>
    <div class="comment_content_container" style="width:<%=@width%>px;">
      <div class="comment_content">
        <%= form_for Comment.new, :remote => true do |f| %>
          <%= f.text_area :content, :rows => '10' %>
          <div class="field" style="display:hidden;">
            <%= f.hidden_field :commentable_id, :value => place.id %>
            <%= f.hidden_field :commentable_type, :value => "Place" %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/comments/_reply_form.html.erb
<% comment = reply_form-%>
<%= form_for Comment.new, :remote => true do |f| %>
  <div class="field">
    <%= f.text_area :content, :rows => '10' %>
  </div>
  <div class="field" style="display:hidden;">
    <%= f.hidden_field :commentable_id, :value => comment.id %>
    <%= f.hidden_field :commentable_type, :value => "Comment" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(@comment.commentable.comments.count, 'Comment') %>");

/* Add the new comment to the bottom of the comments list */
$(".show_comments").prepend("<%= escape_javascript(render(@comment)) %>");

/* Reset the comment form */
$('#new_comment')[0].reset();

/* Highlight the new comment */
$("#comment_<%= @comment.id %>").effect("highlight", {}, 3000);

app/views/comments/destroy.js.erb
/* Eliminate the comment by fading it out */
$('#comment_<%= @comment.id %>').fadeOut();
/* Replace the count of comments */
$("#comments_count").html("<%= pluralize(@comment.commentable.comments.count, 'Comment') %>");

app/views/home/_activity.html.erb
<div>
  <div>
  <% if Place === activity %>
    <h3><%=link_to activity.name, activity %></h3>
    <p><%= activity.address%></p>
    <p><%= activity.designation_list %></p>
  <% elsif Comment === activity %>
    <p><%= activity.content %></p>
  <% end %>
  <p>Created by <%= activity.user.username %> <%= distance_of_time_in_words_to_now activity.created_at %> ago</p>

</div>

app/views/home/_footer.html.erb
<div id="the_footer" class="bound block">
  <h3> Just a little footsie </h3>
</div>

app/views/home/_header.html.erb
<div id="the_header" class="bound">
    <h1> <%= link_to "ParkPlace", root_url %> </h1>
    <div id="navigation">  
      <ul class="primary">
        <% if user_signed_in? %>  
          <li class="nav_item"> <%= link_to "Map", "/map/index" %></li>
          <li class="nav_item"> <%= link_to "Sign out", destroy_user_session_path %></li>
          <li class="nav_item"> <%= link_to "Edit profile", edit_user_registration_path %> </li> 
        <% else %>  
          <li class="nav_item"> <%= link_to "Map", "/map/index" %></li>
          <li class="nav_item"> <%= link_to "Sign up", new_user_registration_path %> </li>
          <li class="nav_item"> <%= link_to "Sign in", new_user_session_path %> </li>
        <% end %>  
      </ul>
    </div> 
</div>
 

app/views/home/_history.html.erb
<% @place = history-%>
<div class="place_compact_rep">
    <h3><%=link_to @place.name, @place %></h3>
    <p><%= @place.address%></p>
    <p><%= @place.designation_list %></p>
    <%= render :partial => "icon_images" %>

</div>

app/views/home/_icon_images.html.erb
<div class="facility_tags">
  <% @place.facility_list.each do |t| %>
    <%= icon_image(t, "icon selected") %>
  <% end %>
</div>

app/views/home/_icons.html.erb
<% @tags.each do |t| %>
  <% if @place.facility_list.include?(t) %>
    <span class="icon_checkbox">
      <%= check_box_tag "facilities[]", t, false, :class => "check_box", :id => t.gsub(' ', '_'), :checked => true %>
      <%= label_tag t, icon_image(t, "editable_icon selected") %>
    </span>
  <% else %>
    <span class="icon_checkbox">
      <%= check_box_tag "facilities[]", t, false, :class => "check_box", :id => t.gsub(' ', '_')%>
      <%= label_tag t, icon_image(t, "editable_icon") %>
    </span>
  <% end %>
<% end %>

app/views/home/index.html.erb
<div id="activity">
  <h2> Recent Activity </h2>
  <%= render :partial => 'activity', :collection => @activity %>
</div>

app/views/home/map.html.erb
<%= javascript_include_tag 'map_index' %>
<div id="map_sidebar">
  <% if @user and @user.admin? %>
    <span id="new_place_link">(<%= link_to 'New', new_place_path %>)</span>
  <% end %>

  <%= render :partial => 'sidebar', :collection => @places %>
</div>

<script type="text/javascript">
  var places = <%= @places.to_json.html_safe %>;
  var inforwindow_content = '<div></div>';
</script>

<div id="map_container">
  <input id="address" type="textbox" size="40" value="Sunset State Beach in CA">
  <input type="button" value="Search" onclick="codeAddress()">
  <input type="button" value="Add Place" onclick="addPlace()">
  <div id="map_canvas"> </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripper</title>
  <%= javascript_include_tag "jquery-1.4.4.min", "jquery.rails.js" %>
  <%= javascript_include_tag 'application' %>

  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="the_top">
    <%= render :partial => "/home/header" %>
  </div>
  <div id="the_middle">
    <div id="the_content" class="bound">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripper</title>
  <%= javascript_include_tag "jquery-1.4.4.min", "jquery-ui-1.8.7.custom.min", "jquery.rails.js" %>
  <%= javascript_include_tag 'application' %>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>

  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'jquery-ui-1.8.7.custom' %>
  <link rel="stylesheet" href="/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="the_top">
    <%= render :partial => "/home/header" %>
  </div>
  <div id="the_middle">
    <div id="the_content" class="bound">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
  <div id="the_bottom">
    <%= render :partial => "/home/footer" %>
  </div>

</body>
</html>

app/views/map/_form.html.erb
<%= form_for(@place) do |f| %>
  <div id="place_errors"></div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => '55' %>
  </div>
  <div> <%= select_tag 'designation', options_for_select([["National Park"], ["Start Park"], ["County Park"], ["City Park"]]) %>  </div>

  <%= render :partial => "/home/icons" %>

  <div class="field" style="display:none;">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/map/_sidebar.html.erb
<% place = sidebar-%>
<div>
  <div class="place_in_sidebar">
    <div class="place_title_in_sidebar">
      <h2><%=link_to place.name, place %></h2>
    </div>
    <p><%=place.address%></p>
    <p><%= place.designation_list %></p>
    <p><%= place.facility_list%></p>

  </div>
</div>

app/views/map/index.html.erb
<%= javascript_include_tag 'map_index' %>
<script type="text/javascript">
  var places = <%= @places.to_json(:methods => :facility_list).html_safe %>;
</script>

<script type="text/javascript">
  var geo = new google.maps.Geocoder();       
  $(function() {
  $( "#map_address" ).autocomplete({
    source: function(request, response) {
        geo.geocode( {'address': request.term}, function(results, status) {
          response($.map(results, function(item) {
            return {
              label: item.formatted_address,
              value: item.formatted_address,
              viewport: item.geometry.viewport,
              location: item.geometry.location
            }
          }));
        })
      },
    minLength: 3,
  });
});
</script>

<div id="map_container">
  <input id="map_address" type="textbox" size="40" value="">
  <input id="code_address" type="button" value="Search" onclick="codeAddress()">
  <input type="button" value="Add Place" onclick="addPlace()">
  <div id="map_canvas"> </div>
</div>

app/views/map/new_place.html.erb
<%= render 'form' %>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% @place.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :size => '55' %>
  </div>
  <div> <%= select_tag 'designation', options_for_select([[],["National Park"], ["State Park"], ["County Park"], ["City Park"]], :selected => @place.designation_list) %>  </div>

  <%= render :partial => "/home/icons" %>

  <fieldset class="buttons actions">
    <%= f.submit  %>
  </fieldset>

<% end %>

app/views/places/_map.html.erb
<script type="text/javascript">
  var place = <%= @place.to_json.html_safe %>.place;
</script>
<div id="map_canvas_for_place"> </div>

app/views/places/_row_summary.html.erb
<% place = row_summary-%>
<tr class="place<%= (place.user == current_user) ? " mine" : "" %>">
  <td class="user"><%= place.user.username %></td>
  <td class="name"><%= link_to place.name, place%></td>
  <td class="address"><%= link_to place.address, place%></td>
  <td class="edit_and_delete_links">
    <% if user_signed_in? and (place.user == current_user or current_user.admin?) %>
      <%= link_to image_tag("edit.png"), edit_place_path(place) %>
      <%= link_to image_tag("remove.png"), place, :confirm => 'Are you sure?', :method => :delete %>
    <% end %>
  </td>
</tr>

app/views/places/_summary.html.erb
<% place = summary -%>
<div>
<p><%=link_to place.name, place %></p>

<div class="metadata">
  <span class="user">Created by <%= place.user.username%></span>
  <span class="timestamp"><%= distance_of_time_in_words_to_now place.created_at %> ago</span>
  <% if user_signed_in? and @user.admin? %>
    <span class="edit_links">
      <%= link_to image_tag("edit.png"), edit_place_path(place) %>
      <%= link_to image_tag("remove.png"),  place, :confirm => 'Are you sure?', :method => :delete %>
    </span>
  <% end %>
</div>

<div class="tags">
  <p>Designation: <%= place.designation_list %> </p>
  <p>Facilities: <%= place.facility_list%> </p>
</div>

<p class="comment_link">
  <% if place.comments.length > 0 %>
    <%= link_to pluralize(place.comments.length, "comment"), place_url(place) + "#comments" %>
  <% else %>
    <%= link_to "no comments", place_url(place) + "#comments" %>
  <% end %>
</p>
</div>

app/views/places/edit.html.erb
<div class="edit_place">
  <div class="block">
    <h2>Editing place</h2>
  </div>
  <div class="place_form">
    <%= render 'form' %>
  </div>

</div>

app/views/places/index.html.erb
<div class="listing_places">
  <h2 class="scaffold">Places</h2>
  <table class="zebra">
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Address</th>
      <th></th>
    </tr>
    <%= render :partial => 'row_summary', :collection => @places %>
  </table>

</div>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<%= javascript_include_tag 'map_for_place' %>
<div class="place_form">
  <div class="place_metadata">
    <h2> 
      <%= @place.name %> 
      <% if user_signed_in? and (@place.user == current_user or current_user.admin?) %>
        <span class="edit_links">
          <%= link_to image_tag('edit.png'), edit_place_path(@place) %>
        </span>
      <% end %>
    </h2>

    <%= render :partial => "/home/icon_images" %>
    <%= link_to 'Back', root_url, :class=>"link" %> |
    <%= link_to 'All places', places_path, :class=>"link" %>
  </div>

  <span id="comments_count"><%= pluralize(@place.comments.count, "Comment") %></span>
  <div class="show_comments">
    <%= render :partial => "comments/comment",
      :collection => @place.comments.reverse %>
  </div>

  <%= render :partial => "comments/place_form", :object => @place %>

</div>

<div id="map_container">
  <%= render :partial => "map" %>
</div>

app/views/users/index.html.erb
<table>
<% for user in @users %>  
  <tr>  
    <td><%= image_tag avatar_url(user) %></td>  
    <td><%= user.email %></td>  
    <td><%= link_to "Show", user %></td>  
    <td><%= link_to "Edit", edit_user_path(user) %></td>  
    <td><%= link_to "Destroy", user, :confirm => 'Are you ↵  
      sure?', :method => :delete %></td>  
  </tr>  
<% end %>  
</table>

app/views/users/show.html.erb
<h1> User Profile Page </h1>
<div>
  This is the profile page of <%= @user.username %>
</div>
<div class="user_created">
  <%= @user.username %> has created <%= pluralize(@places.length, 'parks') %>
  <%= render :partial => '/places/summary', :collection => @places %>
</div>

<div class="user_visited">
  <%= @user.username %> has visited <%= pluralize(@places.length, 'parks') %>
  <%= render :partial => '/places/summary', :collection => @places %>
</div>